### ISSUE TITLE
Duplicated directives, clauses, and grammar rules

### ISSUE THREAD

**Issue by pmoura** [SWI-Prolog/packages-cql#4]
From the Logtalk linter:

```
*     Duplicated directive: public cql_history_attribute/3
*       while compiling object cql
*       in file /Users/pmoura/lib/swipl/library/cql/cql.pl between lines 44-101
*     
```

```
*     Duplicated directive: multifile check:valid_string_goal/1
*       while compiling object sql_tokenizer
*       in file /Users/pmoura/lib/swipl/library/cql/sql_tokenizer.pl at or above line 102
*     
*     Duplicated grammar rule found around line 148: sql_token(',')-->",",!
*       while compiling object sql_tokenizer
*       in file /Users/pmoura/lib/swipl/library/cql/sql_tokenizer.pl at or above line 147
```

```
*     Duplicated clause found around line 117: reserved_sql_keyword(end)
*       while compiling object sql_keywords
*       in file /Users/pmoura/lib/swipl/library/cql/sql_keywords.pl at or above line 116
*     
*     Duplicated clause found around line 121: reserved_sql_keyword(exec)
*       while compiling object sql_keywords
*       in file /Users/pmoura/lib/swipl/library/cql/sql_keywords.pl at or above line 118
*     
*     Duplicated clause found around line 273: reserved_sql_keyword(substring)
*       while compiling object sql_keywords
*       in file /Users/pmoura/lib/swipl/library/cql/sql_keywords.pl at or above line 229
```

**Comment by JanWielemaker** [comment]
Its not my code :)  I didn't expect much from a duplicate clause check but I'm afraid I'm proven to be wrong ....

**Comment by pmoura** [comment]
I know. But you likely are in contact with the author?

Duplicated clauses and grammar rules usually don't result in wrong solutions or failed queries but can introduce spurious choice-points and thus degrade performance.

**Comment by JanWielemaker** [comment]
Sure I know the authors.   I think I'll simply delete the duplicate clauses and inform the authors though.   That will be tomorrow.

**Comment by JanWielemaker** [comment]
Duplicate clause checks surely make sense.   I decided to leave the duplicate multifile and they are in conditional code.  This way the conditional code stays a unit.  One might argue that as they depend on the same condition they should be merged, but the current placement also makes sense.

**Comment by pmoura** [comment]
W.r.t. to the leaving the duplicated multifile directive in-place, I don't see redundancy in general as necessarily a bad thing. But a linter should always flag these cases. It prevents someone later maintaining the code changing one directive not realizing there's a duplicate elsewhere.
